version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
      - image: neo4j:3.2.7-enterprise
        environment:
          NEO4J_AUTH: none
          NEO4J_HEAP_MEMORY: 256
          NEO4J_CACHE_MEMORY: 256M

    working_directory: /go/src/github.com/Financial-Times/public-annotations-api
    environment:
          NEO4J_TEST_URL: "http://localhost:7474/db/data/"
          CIRCLE_TEST_REPORTS: /tmp/test-reports
          CIRCLE_COVERAGE_REPORT: /tmp/coverage-results

    steps:
      - checkout
      - run:
          name: Make go get work
          command: sudo chown -R circleci:circleci /go/src
      - run:
          name: Create test folder
          command: |
            mkdir -p ${CIRCLE_TEST_REPORTS}
            mkdir -p ${CIRCLE_COVERAGE_REPORT}
      - run:
          name: External Dependancies
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            go get -u github.com/jstemmer/go-junit-report
            go get -u github.com/mattn/goveralls
      - run: |
          dep ensure -v -vendor-only
      - run: |
          go build -v
      - run:
          wget --retry-connrefused --no-check-certificate -T 60 $NEO4J_TEST_URL; curl $NEO4J_TEST_URL
      - run: |
          go test ./... -v -race -cover -coverprofile=$CIRCLE_COVERAGE_REPORT/coverage.out | go-junit-report > $CIRCLE_TEST_REPORTS/junit.xml
      - run: |
          goveralls -coverprofile=$CIRCLE_COVERAGE_REPORT/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - store_test_results:
          path: /tmp/test-reports
          
  dredd:
    working_directory: /go/src/github.com/Financial-Times/public-annotations-api
    docker:
      - image: bankrs/golang-dredd:go1.10.0-dredd5.0.0
        environment:
          GOPATH: /go
          NEO4J_TEST_URL: "http://localhost:7474/db/data/"
    steps:
      - checkout
      - run:
          name: External Dependencies
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            go get -u github.com/mattn/goveralls
            go get -u github.com/jstemmer/go-junit-report
      - run:
          name: Load ersatz-fixtures.yml to ersatz image
          command: "curl -X POST --data-binary @_ft/ersatz-fixtures.yml -H \"Content-type: text/x-yaml\" http://localhost:9000/__configure"
      - run:
          name: Import libraries
          command: dep ensure -v -vendor-only
      - run:
          name: Go Build
          command: go build -v
      - run:
          name: Dredd API Testing
          command: dredd
  docker_build:
    working_directory: /public-annotations-api
    docker:
      - image: docker:18.03
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build Dockerfile
          command: docker build .

workflows:
  version: 2
  tests_and_docker:
    jobs:
      - build
      - docker_build:
          requires:
            - build
